#!/usr/bin/env bash
set -euo pipefail

# module/module.json's "id" is the single source of truth for this module's
# identity. Tsuki's steamlaunchext.lua namespaces every steam-launch-extension
# module's fixed runtime-binding env vars by this same id (env_id(): "M" plus
# uppercase hex of every UTF-8 byte), so the payload must derive the identical
# collision-free token rather
# than hand-writing it a second time in C++ and risking drift if module.json's
# id ever changes.
MODULE_ID="$(jq -r .id ./module/module.json)"
ENV_ID="M$(printf '%s' "$MODULE_ID" | od -An -tx1 | tr -d ' \n' | tr '[:lower:]' '[:upper:]')"

TEMPORARY="$(mktemp ./src/.ronin_env.hpp.XXXXXX)"
trap 'rm -f -- "$TEMPORARY"' EXIT HUP INT TERM
printf '%s\n' "#pragma once

// Generated by embed-module-env.sh from module/module.json's \"id\" field.
// Do not hand-edit; do not hardcode this token elsewhere.
constexpr const char* kRoninEnvId = \"$ENV_ID\";" > "$TEMPORARY"
if ! cmp -s -- "$TEMPORARY" src/ronin_env.hpp; then
	mv -f -- "$TEMPORARY" src/ronin_env.hpp
else
	rm -f -- "$TEMPORARY"
fi
trap - EXIT HUP INT TERM
