#pragma once

// Generated by embed-module-env.sh from module/module.json's "id" field.
// Do not hand-edit; do not hardcode this token elsewhere.
constexpr const char* kRoninEnvId = "M736C737465616D";
